config/routes.rb
Rails.application.routes.draw do
  resources :sudokus
  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :sudokus
end

app/models/sudoku.rb
class Sudoku < ActiveRecord::Base
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :nick)
    end
end

app/controllers/sudokus_controller.rb
class SudokusController < ApplicationController
  before_action :set_sudoku, only: [:show, :edit, :update, :destroy]

  # GET /sudokus
  # GET /sudokus.json
  def index
    @sudokus = Sudoku.all
  end

  # GET /sudokus/1
  # GET /sudokus/1.json
  def show
  end

  # GET /sudokus/new
  def new
    @sudoku = Sudoku.new
  end

  # GET /sudokus/1/edit
  def edit
  end

  # POST /sudokus
  # POST /sudokus.json
  def create
    @sudoku = Sudoku.new(sudoku_params)

    respond_to do |format|
      if @sudoku.save
        format.html { redirect_to @sudoku, notice: 'Sudoku was successfully created.' }
        format.json { render :show, status: :created, location: @sudoku }
      else
        format.html { render :new }
        format.json { render json: @sudoku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sudokus/1
  # PATCH/PUT /sudokus/1.json
  def update
    respond_to do |format|
      if @sudoku.update(sudoku_params)
        format.html { redirect_to @sudoku, notice: 'Sudoku was successfully updated.' }
        format.json { render :show, status: :ok, location: @sudoku }
      else
        format.html { render :edit }
        format.json { render json: @sudoku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sudokus/1
  # DELETE /sudokus/1.json
  def destroy
    @sudoku.destroy
    respond_to do |format|
      format.html { redirect_to sudokus_url, notice: 'Sudoku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sudoku
      @sudoku = Sudoku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sudoku_params
      params.require(:sudoku).permit(:difficulty, :time, :solution, :player_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sudokus_helper.rb
module SudokusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sudoku Puzzle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<div class="form" style="position: absolute;  top: 50%; left: 50%; width: 800px; height: 600px; margin-left: -220px; margin-top: -200px; font-size: 24px; color: gray; opacity: 0.8;">
  <%= form_for(@player) do |f| %>
    <% if @player.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

        <ul>
        <% @player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :nick %><br>
      <%= f.text_field :nick %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/players/edit.html.erb
<div class="form">
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>
</div>

app/views/players/index.html.erb
<div class="form">
<p id="notice"><%= notice %></p>

<h1>Welcome to Sudoku game!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nick</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.nick %></td>
        <td><%= link_to 'Show', player %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>
</div>

app/views/players/new.html.erb
<div class="form">
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>
</div>

app/views/players/show.html.erb
<div class="form">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Nick:</strong>
  <%= @player.nick %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>
<br><br><br>
<input id="playButton" type="button" style="color: #FFF; background-color: #900; font-size: 150%; text-transform: uppercase;" onclick="location.href='/sudokus/new'" value="Begin to play"/>
</div>

app/views/sudokus/_form.html.erb
<div class="form">
  <%= form_for(@sudoku) do |f| %>
    <% if @sudoku.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@sudoku.errors.count, "error") %> prohibited this sudoku from being saved:</h2>

        <ul>
        <% @sudoku.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :difficulty %><br><br>
      <%= f.label :difficulty, "Easy", :value => "Easy"  %>
      <%= f.radio_button :difficulty, "easy", :checked => true %><br><br>
      <%= f.label :difficulty, "Medium", :value => "Medium"  %>
      <%= f.radio_button :difficulty, "medium"%><br><br>
          <%= f.label :difficulty, "Hard", :value => "Hard"  %>
      <%= f.radio_button :difficulty, "hard" %><br><br>
    </div>
    <div class="field">
      <%= f.label :player_id %><br>
      <%= f.text_field :player_id %>
    </div><br>
    <div class="actions">
      <%= f.submit :PLAY %>
    </div>
  <% end %>   
</div>

app/views/sudokus/edit.html.erb
<div class="form">
	<h1>Editing Sudoku</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @sudoku %> |
	<%= link_to 'Back', sudokus_path %>
</div>

app/views/sudokus/index.html.erb
<div class="form">
  <p id="notice"><%= notice %></p>

  <h1>Listing Sudokus</h1>

  <table>
    <thead>
      <tr>
        <th>Difficulty</th>
        <th>Time</th>
        <th>Solution</th>
        <th>Player</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sudokus.each do |sudoku| %>
        <tr>
          <td><%= sudoku.difficulty %></td>
          <td><%= sudoku.time %></td>
          <td><%= sudoku.solution %></td>
          <td><%= sudoku.player_id %></td>
          <td><%= link_to 'Show', sudoku %></td>
          <td><%= link_to 'Edit', edit_sudoku_path(sudoku) %></td>
          <td><%= link_to 'Destroy', sudoku, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Sudoku', new_sudoku_path %>
</div>

app/views/sudokus/new.html.erb
<div class="form">
	<h1>New Sudoku</h1>

	<%= render 'form' %>

	<%= link_to 'Back', sudokus_path %>
</div>